name: Build and Release Firmware

on:
  push:
    tags:
      - "v*"

permissions:
contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO + dotenv
        run: |
          pip install --upgrade platformio
          pip install python-dotenv

      - name: Build firmware
        run: pio run -e esp32dev

      - name: Upload firmware to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: .pio/build/esp32dev/firmware.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

